### ISSUE TITLE
Make areas (markers) on map a more contrasting colour

### ISSUE THREAD

**Issue by tomford92** [isjeffcom/coronvirusFigureUK#4]
Hi there,

Love what youve made here! It's useful and getting shared quite widely in my circles! Great job.

Wondering if you could make a design change - to make the marked areas on the map have a bit more contrast to the map itself. Especially when you zoom right down to very local level, the circles shrink down to a tiny size, and given current colour it can be hard to see them. Take a look at 'Bradford' as an example of this, i've attached a screenshot.

![bradford](https://user-images.githubusercontent.com/27225710/76604618-fdc55a80-6506-11ea-8277-5d093127e30f.jpg)

Thanks!

**Comment by isjeffcom** [comment]
Thanks for your feedback. I've tried to address this issue.

The main problem is the marker size. The problem is not easy to be resolve as only England and Scotland has detailed regional data and Wales and Northern Ireland were treated as a whole. Therefore it's hard to find a perfect coefficient for visualization.

The best way to address this problem is:
Use a styled map like Mapbox, however, the cost is too expansive as the traffic is much higher than the free limit is provided. (Mapbox cost me 170 USD in first 2 days)

Or maybe I could find a better way... I've updated a version and you can see if it's going to work.

BTW: the front-end has it's own repository as the API only provides data.
https://github.com/isjeffcom/covid-19-datav-uk

**Comment by tomford92** [comment]
markers look a bit bigger now, certainly makes a difference! Thanks dude.
